### ISSUE TITLE
3과제

### ISSUE THREAD

**Issue by ansangg00** [ansanGroup/Memorize-until-27th#1]
// 슬라이드
var Slider = function(opt){
	var timer;
	var cnt = 0;
	var def = {
		sec:1500,
		max_cnt: 3,
		callback:function(){}
	}

	opt = $.extend(def,opt);

	this.move = function(c){
		if(c < 0) c = opt.max_cnt - 1;
		if(c >= opt.max_cnt) c = 0;
		cnt = c;
		opt.callback(c);
	}

	this.prev = function(){this.move(cnt - 1)}
	this.next = function(){this.move(cnt + 1)}
}

$(function(){
	$("#slider>div>div").eq(1).append("<div></div>");
	$("#slider>div>div>div").append(`
		<img src="i/Slide1.jpg" alt="img" />
		<img src="i/Slide2.jpg" alt="img" />
		<img src="i/Slide3.jpg" alt="img" />
	`);
	$("#slider>div>div").eq(1).css({position:"relative",overflow:"hidden"});
	$("#slider>div>div>div").css({position:"absolute",width:"300%",margin:"0"});
	$("#slider img").css({width:"33.333%",float:"left"});

	var slider = new Slider({
		callback: function(c){
			$("#slider>div>div>div").stop().animate({left:-c*100+"%"});
		}
	})

	$("#slider>div>div").eq(0).click(function(){
		slider.prev();
	})
	$("#slider>div>div").eq(2).click(function(){
		slider.next();
	})
//슬라이드

//메뉴 이동
	$("nav ul li a").on("click", function(e){
		e.preventDefault();

		var index = $(this).parent().index() - 1;
			position = ["#result","#photo","#competition41","#about"];

		$("html, body").animate({
			"scrollTop": $(position[index]).offset().top
		}, 1000); 
	})
//메뉴 이동 끝
//CSS
	$("#competition40").css({"min-height":"430px"});

	$("#photo>div").css({margin:"auto"})

	$("#result > div > div > ul > li > ul > li").click(function(){
//CSS
//사진
	var is = $(this),
			data = {
				gameInfo:is.parent().parent().parent().parent().children('h2').html(),
				name:is.html(),
				country:is.attr('data-country'),
				title:is.attr('title')
			},
			html = "";

		html += "<div>";
			// 이  이미지는 선수사진을 사용해야 합니다
			html += "<img src='i/Slide1.jpg' alt='slider' />"; 
			html += "<p>";
				html += "대회년도와 도시 : " + data.gameInfo;
			html += "</p>";
			html += "<p>";
				html += "선수이름 : " + data.name;
			html += "</p>";
			html += "<p>";
				html += "국가 : " + data.country;
			html += "</p>";
			html += "<p>";
				html += "메달 종류 : " + data.title;
			html += "</p>";
		html += "</div>";

		$(html).dialog({
			close:function () {
				$(".ui-dialog").remove();
			},
			width:720,
			height:500
		});
	})
//사진
	// 빼럴뤡스 쓰크뢀링

	this.setParrellex = function () {
		var wTop = $(window).scrollTop();

		var about = 50 + (wTop - $("#about").offset().top) * 0.5;
		$("#about").css({
			'background-position': '80% '+about+'%'
		});

		var competition41 = 50 + (wTop - $("#competition41").offset().top) * 0.3;
		$("#competition41").css({
			'background-position': '20% '+competition41+'%'
		});

		var competition40 = 50 + (wTop - $("#competition40").offset().top) * 0.5;
		$("#competition40").css({
			'background-position': '80% '+competition40+'%'
		});
	}
		// 각 영역에 패럴렉스 스크롤링을 위한 백그라운드 적용
		$("#about").css({
			'background':'url(i/about.png)',
			'background-size': '30%',
			'background-repeat': 'no-repeat',
			'background-position': '80% 50%'
		});

		$("#competition41").css({
			'background':'url(i/41.png)',
			'background-size': '30%',
			'background-repeat': 'no-repeat',
			'background-position': '20% 50%'
		});

		$("#competition40").css({
			'background':'url(i/40.png)',
			'background-size': '30%',
			'background-repeat': 'no-repeat',
			'background-position': '80% 50%'
		});

	// 빼럴뤡스 쓰크뢀링
	$(window).scroll(this.setParrellex);

	// read more
	this.readMore = function () {
		$(this).parent().find('.hidden-text').show('slow');
		$(this).hide();
	}
		// read more 스타일을 위한 것들
		$(".hidden-text").parent().append('<a href="javascript:void(0);" class="read-more">read more</a>');
		
	// read more
	$("body")
	.on('click', '.read-more', this.readMore);

			// photo 효과를 위한 것들
			$("#photo img").css({
				'transition':'0.5s all',
				'box-shadow':'0 0 10px rgba(0,0,0,0)'
			});
		// photo section
		$("#photo")
		.on('mouseover', 'img', function () {
			$(this).css({
				'transform':'scale(1.2)',
				'box-shadow':'0 0 10px rgba(0,0,0,0.8)'
			},500);
		})
		.on('mouseout', 'img', function () {
			$(this).css({
				'transform':'scale(1)',
				'box-shadow':'0 0 10px rgba(0,0,0,0)'
			},500);
		})
		.on('click', 'img', function () {
			var src = $(this).attr('src'),
				html = "";

			src = 'i/big_' + src.replace('i/', '');

			html += '<div>';
				html += '<img src="'+src+'" alt="big_img"/>';
			html += '</div>';

			$(html).dialog({
				close:function () {
					$(".ui-dialog").remove();
				},
				width:690,
				height:500
			});
		});
})

**Comment by ansangg08** [comment]
오케
